name: Plugin Verifier

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - master
        tags:
            - '*'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    java-version: '11'
                    distribution: 'adopt'
            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
            -   name: Build plugin
                uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
                with:
                    arguments: build
            -   name: Verify plugin
                uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
                with:
                    arguments: runPluginVerifier

            # If it is a tag push, release it automatically to the Jetbrains marketplace
            -   name: Publish plugin
                uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
                with:
                    arguments: publishPlugin
                if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
