name: Publish

on:
    workflow_dispatch:
    push:
        tags:
            - "v*"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'zulu'

            -   name: Verify plugin
                uses: gradle/gradle-build-action@v2.4.0
                with:
                    arguments: runPluginVerifier

            -   name: Publish plugin
                uses: gradle/gradle-build-action@v2.4.0
                with:
                    arguments: publishPlugin
                env: # Or as an environment variable
                    PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
                    PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
                    PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                    CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
