name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3.1
        with:
          linter: jetbrains/qodana-jvm-community
