name: Test

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - master
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'zulu'

            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@v1
            -   name: Test plugin
                uses: gradle/gradle-build-action@v2.9.0
                with:
                    arguments: test
            -   name: Verify plugin
                uses: gradle/gradle-build-action@v2.9.0
                with:
                    arguments: runPluginVerifier
concurrency:
    group: ${{github.workflow}}-${{github.head_ref || github.run_id }}
    cancel-in-progress: true
